---
title: "Reglas de asociación"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r paquetes}
if(! "arules" %in% installed.packages()) install.packages("arules", depend = TRUE)
if(! "arulesViz" %in% installed.packages()) install.packages("arulesViz", depend = TRUE)
library(arules)
library(dplyr)
library(arulesViz)
```

```{r}
movies<- read.csv("datos/movies_2026.csv")
colnames(movies)
```

```{r preparando datos}

cols <- c("genres",
          "originalLanguage",
          "productionCountry")

# Convertir en factor las categóricas y discretizar las numéricas
datos <- movies %>%
  select(genres,
         originalLanguage,
         productionCountry,
         budget,
         revenue,
         runtime,
         voteAvg,
         popularity,
         releaseYear) %>%
  
  mutate(across(all_of(cols), as.factor)) %>%
  
  mutate(across(!all_of(cols),
                ~ discretize(.,
                             method = "frequency",
                             breaks = 3)))
# Convertir a transaccioens
trans <- as(datos, "transactions")
```

```{r a priori}
rules <- apriori(trans,
                 parameter = list(support = 0.01,
                                  confidence = 0.6,
                                  minlen = 2))
inspect(rules)
```

```{r}
# Punto 2
rules_estrictas <- apriori(trans,
                           parameter = list(support = 0.005,
                                            confidence = 0.8,
                                            minlen = 2))
cat("Reglas estrictas encontradas:", length(rules_estrictas), "\n")
```

```{r}
# 1. Gráfica ANTES de quitar características
top_rules_originales <- head(sort(rules, by = "confidence"), 20)

plot(top_rules_originales, method = "graph", 
     engine = "htmlwidget", 
     main = "Top 20 Reglas (Todas las variables - Antes de limpiar)")
```

```{r}
# 2. Eliminación de características muy frecuentes y reducción de muestra
set.seed(123)

datos_filtrados <- datos %>%
  select(-originalLanguage, -productionCountry) %>%
  sample_n(3000) 

trans_filtradas <- as(datos_filtrados, "transactions")

rules_limpias <- apriori(trans_filtradas,
                         parameter = list(support = 0.02,
                                          confidence = 0.6,
                                          minlen = 2))

rules_interesantes <- sort(rules_limpias, by = "lift")


inspect(head(rules_interesantes, 10))
```

```{r}
# 3. Gráfica DESPUÉS de quitar características
top_rules_limpias <- head(rules_interesantes, 20)

plot(top_rules_limpias, method = "graph", 
     engine = "htmlwidget",
     main = "Top 20 Reglas (Sin Idioma ni País - Después de limpiar)")

# 4. Gráfica de Dispersión
plot(rules_limpias, method = "scatterplot", 
     measure = c("support", "confidence"), shading = "lift", 
     main = "Dispersión de las reglas limpias")
```




