---
title: "Análisis t-SNE - CineVision Studios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rtsne)
library(ggplot2)
```

```{r}
# dataset original
movies <- read.csv("datos/movies_2026.csv")

numericas <- c("budget", "revenue", "runtime", "popularity", "voteCount", "voteAvg")
movies_num <- movies[, numericas]

movies_num[is.na(movies_num)] <- 0

# Escalar los datos
datos_escalados <- scale(movies_num)
```

```{r}
set.seed(123)
# Tomar muestra y eliminar duplicados
idx <- sample(nrow(datos_escalados), 500)
muestra_tsne <- unique(datos_escalados[idx, ])

# Correr el algoritmo
tsne_results <- Rtsne(muestra_tsne, 
                      dims = 2, 
                      perplexity = 15, 
                      verbose = FALSE, 
                      max_iter = 500)


tsne_plot_data <- as.data.frame(tsne_results$Y)
colnames(tsne_plot_data) <- c("Dim1", "Dim2")
```

```{r}
ggplot(tsne_plot_data, aes(x = Dim1, y = Dim2)) +
  geom_point(color = "#2c3e50", alpha = 0.7, size = 2) +
  labs(title = "Visualización t-SNE para CineVision Studios",
       subtitle = "Reducción de dimensionalidad no lineal (n=500)",
       x = "Dimensión 1", 
       y = "Dimensión 2") +
  theme_minimal()
```

